# Generated by Django 4.1.7 on 2023-05-11 16:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0092_delete_jobresult'),
        ('dcim', '0171_cabletermination_change_logging'),
        ('netbox_lifecycle', '0004_supportcontractassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportcontract',
            name='manufacturer',
        ),
        migrations.CreateModel(
            name='SupportSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('sku', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.manufacturer')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['manufacturer', 'sku'],
            },
        ),
        migrations.AddField(
            model_name='supportcontractassignment',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_lifecycle.supportsku'),
        ),
    ]
