# Generated by Django 4.1.7 on 2023-05-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lifecycle', '0007_alter_hardwarelifecycle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcontractassignment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='netbox_lifecycle.supportcontract'),
        ),
        migrations.AlterField(
            model_name='supportcontractassignment',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='netbox_lifecycle.supportsku'),
        ),
    ]
