# Generated by Django 4.1.7 on 2023-05-12 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0171_cabletermination_change_logging'),
        ('netbox_lifecycle', '0008_alter_supportcontractassignment_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseassignment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='dcim.device'),
        ),
    ]
