# Generated by Django 5.0.8 on 2024-09-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_lifecycle", "0011_alter_supportcontractassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwarelifecycle",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="hardwarelifecycle",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="license",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="license",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="licenseassignment",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="licenseassignment",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="supportcontract",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supportcontract",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="supportcontractassignment",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supportcontractassignment",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="supportsku",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supportsku",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="vendor",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
