# Generated by Django 5.0.9 on 2025-03-13 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0190_nested_modules'),
        ('netbox_lifecycle', '0014_rename_last_contract_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportcontractassignment',
            options={'ordering': ['contract', 'device', 'license', 'module']},
        ),
        migrations.AddField(
            model_name='supportcontractassignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='dcim.module'),
        ),
    ]
