# Generated by Django 6.0.5 on 2026-06-11 18:54

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0236_moduletype_component_counts'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_lifecycle', '0018_netbox_v040500'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EoXAPISettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('driver', models.CharField(default='cisco')),
                ('url', models.URLField(max_length=300)),
                ('enabled', models.BooleanField(default=False)),
                ('client_id', models.CharField(blank=True, max_length=200)),
                (
                    '_client_secret',
                    models.CharField(
                        blank=True, db_column='client_secret', max_length=500
                    ),
                ),
                ('sync_interval', models.PositiveIntegerField(default=1440)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                (
                    'manufacturers',
                    models.ManyToManyField(
                        related_name='eox_settings', to='dcim.manufacturer'
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'EoX API Settings',
                'verbose_name_plural': 'EoX API Settings',
                'ordering': ('driver', 'url', 'pk'),
                'permissions': (('sync', 'Trigger an EoX sync'),),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('driver', 'url'),
                        name='netbox_lifecycle_eoxapisettings_unique_driver_url',
                        violation_error_message='An EoX settings record for this driver and URL already exists.',
                    )
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
