# Generated by Django 6.0.5 on 2026-06-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0236_moduletype_component_counts'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_lifecycle', '0019_eoxapisettings'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eoxapisettings',
            options={
                'ordering': ('driver', 'manufacturer', 'pk'),
                'permissions': (('sync', 'Trigger an EoX sync'),),
            },
        ),
        migrations.RemoveConstraint(
            model_name='eoxapisettings',
            name='netbox_lifecycle_eoxapisettings_unique_driver_url',
        ),
        migrations.AddField(
            model_name='eoxapisettings',
            name='manufacturer',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='eox_settings',
                to='dcim.manufacturer',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eoxapisettings',
            name='last_synced',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='eoxapisettings',
            constraint=models.UniqueConstraint(
                fields=('driver', 'manufacturer'),
                name='netbox_lifecycle_eoxapisettings_unique_driver_manufacturer',
                violation_error_message='An EoX settings record for this driver and manufacturer already exists.',
            ),
        ),
        migrations.RemoveField(
            model_name='eoxapisettings',
            name='manufacturers',
        ),
        migrations.RemoveField(
            model_name='eoxapisettings',
            name='url',
        ),
    ]
