# Generated by Django 6.0.5 on 2026-07-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lifecycle', '0020_alter_eoxapisettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoxapisettings',
            name='driver',
            field=models.CharField(default='cisco', max_length=50),
        ),
    ]
